### ISSUE TITLE
ImportError: cannot import name 'cusolver'

### ISSUE THREAD

**Issue by zhenzey** [ElArkk/jax-unirep#110]
Thanks for making this package. It is super helpful!

I had no problem install jax-unirep using pip, but when I was trying to import it in Python, the error "ImportError: cannot import name 'cusolver'" comes up. I saw some issues related on Github saying that it is mainly because of the version of Jax. But the package is compatible with Jax version < 0.2.0, so I can not really update Jax. Could you help me with it? I am using python3.6.9, 
Ubuntu 18.04. Thanks!

**Comment by ericmjl** [comment]
Hi @zhenzey! We need to cut a new version pretty soon. I also encountered a similar issue previously.

@ElArkk, I'll go ahead and do the new release. This one should be an easy thing for me to handle.

**Comment by ericmjl** [comment]
@zhenzey, please try install jax-unirep from PyPI. The latest version was just released today (9 May 2021).

**Comment by ElArkk** [comment]
Closing this as no more complaints showed up regarding this matter.
