### ISSUE TITLE
RuntimeError: Resource exhausted: Failed to allocate request for 87.48GiB (93935126000B) on device ordinal 0

### ISSUE THREAD

**Issue by DorJake** [ElArkk/jax-unirep#35]
Thanks for you sharing you work!
I am getting an error message when trying to reproduce gfp_prediction.ipynb,The message is:RuntimeError: Resource exhausted: Failed to allocate request for 87.48GiB (93935126000B) on device ordinal 0.
![Screenshot from 2020-04-09 23-35-23](https://user-images.githubusercontent.com/33484176/78912971-e30ce400-7aba-11ea-915e-56cd37c2c8a2.png)

**Comment by ericmjl** [comment]
@DorJake thank you! It sounds like memory allocation might be an issue here. That's something all of us have to deal with. In our case, we've been lucky to work on an HPC system.

My first hypothesis is that subsampling the data will let you run the GFP example on your local machine. Try subsampling just 10 sequences first, and then gradually grow the number to see when you hit the limit of your system's RAM. Then, harnessing some of your own Python-fu, you should be able to get_reps over batches of data. :smile: Let us know if even that's an issue, then there might be some deeper things to debug on your Linux system.

**Comment by ElArkk** [comment]
Hi @DorJake ! I re-ran the notebook on my laptop, and while `get_reps` seemingly runs forever when I try to encode all 50'000+ sequences at once, doing 1000 sequences at a time only takes about 1 minute on CPU. I did not encounter any memory allocation issues in both cases though, which might hint at a problem in your `jax` installation.

I hope you were successful in encoding the sequences using a batching approach as @ericmjl suggested. I'm going to close this issue for now, but please come back to us if you have any more questions!
