### ISSUE TITLE
2 sets of weights in weights folder?

### ISSUE THREAD

**Issue by ivanjayapurna** [ElArkk/jax-unirep#41]
Kind of a random thing I noted, there are 2 sets of weights in the weights folder both titled the same thing but one has capitalization. Is there a difference between these weights? Do they both need to be there?

**Comment by ElArkk** [comment]
Hi @ivanjayapurna! Good catch, they are actually the same weights. Only one of them is needed. IIRC, I changed the folder name to be all lowercase in the past, but git somehow by default ignores case changes and something got messed up.
Fixed now!
