### ISSUE TITLE
dump_params function saves dense params with switched filenames

### ISSUE THREAD

**Issue by andrewfavor95** [ElArkk/jax-unirep#42]
The dump_params function saves switched names for the "fully_connected_biases/0.npy", and "fully_connected_weights/0.npy" files.  This causes errors with input parameter shapes when trying to reload these saved weights using the load_params function.

**Comment by ElArkk** [comment]
Hi @andrewfavor95, you are right, thank you for catching that and raising the issue! 
Should be fixed now. Let me know if you still encounter problems.
We should definitely write shape tests for all params dumping and loading functions.

**Comment by ElArkk** [comment]
Tests are live and the issue seems fixed, going to close this.
