### ISSUE TITLE
How can I use 'get_reps' on many long amino acid squences?

### ISSUE THREAD

**Issue by KotaroTsuboyama** [ElArkk/jax-unirep#44]
Hi, 

This jax-unirep is really nice, and now I am trying many things.

When I tried getting h_avg for ~1000 sequences with 250-2000 amino acids, I got the following error.
> RuntimeError: Resource exhausted: Out of memory while trying to allocate 16853216 bytes.
or
> Out of memory while trying to allocate 1185258000 bytes.

I have already tried submitting a single sequence to 'get_unirep' like this (df is DataFrame that contains amino acid sequences), but I got the similar 'out of memory' error at after running 100 sequences.
>for i in tqdm(range(len(df))):
>    h_final, c_final, h_avg = get_reps(df['sequence'][I])
>    h_avg_list[i] = h_avg

>ElArkk commented 
>I re-ran the notebook on my laptop, and while get_reps seemingly runs forever when I try to >encode all 50'000+ sequences at once, doing 1000 sequences at a time only takes about 1 >minute on CPU. I did not encounter any memory allocation issues in both cases though.

According to ElArkk's comment, memory itself may not be related to this error because  I am now using 4xCPU + 25GB memory + 16GB Nvidia GPU Linux machine.

I am now wondering how I can solve this issue. 
Thanks!

**Comment by ericmjl** [comment]
Hi @KotaroTsuboyama, it looks to me like you're using jax with GPU enabled. The OOM error at 16853216 bytes appears to match 16GB of GPU RAM, and it looks to me like you're allocating RAM on the GPU and not your CPU.

JAX has some pretty good docs on how to handle GPU out-of-memory errors. Can you see if trying this out works? https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

In both @ElArkk and my case, we've never gotten JAX on GPU working on our work systems, because our systems are old ☹️ , and so we've had to get really creative by working with CPU-only. You're pretty lucky to have a nice modern GPU!

**Comment by KotaroTsuboyama** [comment]
Thank you for your swift replay!

16,853,216 bytes ~ 16MB, I think, but am I wrong??

Actually, I have also tried CPU-based method (without GPU), but I got a similar error. (and the number of bytes are way lower than limitation)

Than you very much for the suggestion! 
The page is related to how to optimize GPU memory allocation, but currently, I only run one jax-unirep for one time (so ~100% GPU memory has already been used for one run of jax-unirep).
So, unfortunately, this may not able to solve my issue.

Also, as written above, I have already try to submit one sequence to 'get-unirep' at one time, but  still, I got a similar error... 

I guess that 'get-unirep' might waste memory at some point, but am I wrong? 
Could you let me know your environment to perform GFP analysis on your paper?

Thanks!!

(PS: actually I do not have GPU, I am just using GPU on google cloud. we can use 16GB GPU ~0.45USD/ one hour!)

**Comment by ericmjl** [comment]
> 16,853,216 bytes ~ 16MB, I think, but am I wrong??

Not at all! My bad, I wasn't looking clearly.

I _think_ the environment we used was a 16GB RAM allocation on our HPC cluster to produce the figures, but @ElArkk will know better. We're using CentOS7 there.

RAM usage in the cloud is unfortunately really hard to debug, as I haven't had much experience doing this, especially if the error is related to memory allocation. (My prior training wasn't in CS, but in biology, please forgive my ignorance on these matters.) 

That said, I have productively dockerized jax-unirep's `get_reps` inside a container with a web API and deployed on a 4GB RAM system, so I'm quite sure our reimplementation can handle limited RAM situations, and I have run the `get_reps` function on another 16GB personal computer that I own.

How does `get_reps` perform on your personal computer? Could you see whether things work there?

**Comment by KotaroTsuboyama** [comment]
>>RAM usage in the cloud is unfortunately really hard to debug
Yeh, I also think so. (My major was not in CS, either..)

Thank you for the suggestion! I will try another environment (including my local laptop) because the current one might be not appropriate for this analysis.

@ElArkk
If you have a suggestion, could you let me know?

**Comment by ElArkk** [comment]
Hi @KotaroTsuboyama, 

Unfortunately I'm no CS major either and I do not have enough understanding of the internals of `jax` to understand what might be going wrong. The one thing I did see is that there are quite a number of issues raised in the `jax` GitHub repository which mention similar errors. Have you checked out their issue tracker yet? 

@ericmjl is right about the computational environment we used for the GFP analysis. 
The python (conda) environment that we used for the jupyter notebook containing the analysis  is the one specified  in the `environment.yml` file.

Sorry not to be of more help here! Please let us know if you find a solution or have any other questions.

**Comment by KotaroTsuboyama** [comment]
Thank you for the suggestion!

> jax GitHub repository which mention similar errors

`According` to your instruction, I can find the solution!
Even when I use for loop to submit one sequence at one time to get_reps (as mention above), I found that GPU memory load was gradually piled up... So, memory clearance should be needed. 

so, as suggested here
https://github.com/google/jax/issues/1222
I used the following code and got no errors!

```
import gc
import jax
def reset_device_memory(delete_objs=True):
    dvals = (x for x in gc.get_objects() if isinstance(x, jax.xla.DeviceValue))
    n_deleted = 0
    for dv in dvals:
        if not isinstance(dv, jax.xla.DeviceConstant):
            try:
                dv._check_if_deleted()  # pylint: disable=protected-access
                dv.delete()
                n_deleted += 1
            except (ValueError,AttributeError):
                pass
        if delete_objs:
            del dv
    del dvals
    gc.collect()
    return n_deleted
```
```
for i in tqdm(range(len(df_sum))):

    h_final_, c_final_, h_avg_ = get_reps(df_sum['sequence'][i])
    h_avg_list[i] = h_avg_
    **reset_device_memory()**
```

Thanks again for your great help, and I hope this suggestion will help someone who gets similar errors related GPU memory
