### ISSUE TITLE
0-th row of embed_matrix:0.npy

### ISSUE THREAD

**Issue by dlnp2** [ElArkk/jax-unirep#46]
Hi, thank you very much for great work (which demonstrates the power of JAX clearly).

Please let me confirm one small point: what is the 0-th array of `embed_matric:0.npy`?
```python
from jax_unirep.utils import load_embedding_1900
embeddings = load_embedding_1900()
print(embeddings.shape)
# (26, 10)
```
The loaded embedding array has 26 rows, but we have only 25 amino acids.
Does this entry correspond to the padding token encoded as 0?

**Comment by ElArkk** [comment]
Hi @dlnp2!

This is a good question that we actually never figured out ourselves. The embedding matrix gets mentioned by one of the original authors in an issue in the original repo:
https://github.com/churchlab/UniRep/issues/14#issuecomment-594261829

He says that the sequences get embedded using a `26 x 10` embedding tensor, but it's true that their integer encoding for the AA only goes from 1 to 25. 

In our implementation, we simply never call the 0th element of the embedding matrix, and our reps look pretty much identical to the original implementation for identical sequences. 

You could be right with your guess that it is the embedding for the padding token! One would need to dig through the TF code in the original repo to find out for sure. We do not use padding in our implementation yet, but length batching instead. We do think about implementing padding though for different batching strategies (see https://github.com/ElArkk/jax-unirep/issues/40).

I hope this helps, let us know if you solve the mystery or have additional questions!

**Comment by dlnp2** [comment]
Thanks a lot for your quick response @ElArkk ! I may have figured out: it indeed embeds the padding token 0.

According to there tutorial script,
- a variable `bucket` is generated by `bucket_op` in which padding operation is done: https://github.com/churchlab/UniRep/blob/master/unirep_tutorial.py#L137
- the variable is then passed to `loss` through `x_placeholder`: https://github.com/churchlab/UniRep/blob/master/unirep_tutorial.py#L221
- `x_placeholder` is one of the operations given by `b.get_rep_ops` (`b` is an instance of `babbler1900` class): https://github.com/churchlab/UniRep/blob/master/unirep_tutorial.py#L152

So, by observing `unirep.py` we can notice that...
- `x_placeholder` above is actually `self._minibatch_x_placeholder` in `babbler1900`: https://github.com/churchlab/UniRep/blob/master/unirep.py#L469
- `self._minibatch_x_placeholder` is used to look up the embedding table: https://github.com/churchlab/UniRep/blob/master/unirep.py#L356
- the table is initialized by `embed_matrix:0.npy` !: https://github.com/churchlab/UniRep/blob/master/unirep.py#L356

Thus combining above, we see that a padded sequence is embedded using `embed_matrix:0.npy` data. The padding constant is 0 by default, so the code should embed padded values using the 0-th row of the numpy data.

**Comment by ericmjl** [comment]
@dlnp2 thanks for this! Looks like we never used the 0th element because we never do any padding, but instead work around the padding problem by batching sequences by length. 

Thinking about padding a bit more here, looks like there are situations where padding could be helpful, for example, when dealing with lots of sequences that are of different lengths, i.e. high shannon diversity w.r.t. lengths of sequences. I'm going to mark this as a "feature request" in a new issue, so we can track it independently.
