### ISSUE TITLE
GFP mutation to sequence question

### ISSUE THREAD

**Issue by wward97** [ElArkk/jax-unirep#60]
Hi! Thank you for providing this github it is extremely helpful! 
In trying to work towards testing evotuning and batching on GFP sequences, as a result I created a script to take the mutation list from https://figshare.com/articles/Local_fitness_landscape_of_the_green_fluorescent_protein/3102154 and turn it into sequences with associated brightness, I did this before noticing that you had already implemented it. One issue I noticed though was that there were 2 quirks with their mutation notation: it is 0 indexed, and the base protein they use does not include an M. 

As quoted https://figshare.com/articles/Local_fitness_landscape_of_the_green_fluorescent_protein/3102154: 

> "Please` note the mutations notation used throughout the files. It is described in details here: http://mixcr.readthedocs.org/en/latest/appendix.html#alignment-and-mutations-encoding. Briefly, all positions are zero-based (i.e. first nucleotide has index 0) and type of mutation (substitution, deletion or insertion) is indicated as the first letter of mutation description. For example, SG101A is the substitution G>A at position 101. The reference avGFP sequence is provided as “avGFP_reference_sequence.fa” file."

Using the wt that is in the GFP notebook in the papers folder, I tested whether the aa replaced is actually the aa specified by the mutation. I did this by adding the below print statement to the mut2seq function which should print first the aa at the desired mutation position and then the aa the mutation claims to be replacing, i then ran it on the first couple entries of the dataframe: 

print(mutant_sequence[position` -1], mut[1])

T A
T A
N N
T I
H M
D L
T A
L Y
N H

However, if we remove the M from the wt and remove the -1 from the index (since their location is already 0 indexed) we get: 

A A
A A
N N
I I
M M
L L
A A
Y Y
H H

Showing the aa being replaced is the one described by the mutation.  
I am not sure if this is intentional or I misunderstood something in the implementation or meaning of the sequences, but any insight would be appreciated!

**Comment by ElArkk** [comment]
Hi @wward97 ,

You are right. We should've actually not added the `M` at the start, and the `-1` indexing is also not necessary. That's a great find, thank you for pointing this out! 

I just re-ran the notebook, using the same prediction pipeline but with the correct mutants, and it actually improved classification accuracy. This shows that UniRep really seems to produce biologically meaningful embeddings!

I will push the updated notebook analysis up soon.

**Comment by ElArkk** [comment]
The updated notebook is pushed. Going to close this.
