### ISSUE TITLE
input_output_pairs memory consumption

### ISSUE THREAD

**Issue by ElArkk** [ElArkk/jax-unirep#75]
As reported by @cschle, trying to embed millions of sequences for use in evotuning leads to huge memory consumption. I think we find the reason when looking at the `xs` and `ys` arrays that `input_output_pairs` produces. Already 10'000 sequences of length 400 generate ~500 MB worth of embeddings (especially the one-hot encoded `ys` array is growing fast):

```python
from jax_unirep.evotuning import input_output_pairs
import sys

s = ["AAFR"*100 for l in range(10000)]
xs, ys = input_output_pairs(s)

sys.getsizeof(xs) * 1e-9 # in gigabytes
```
0.16
```python
sys.getsizeof(ys) * 1e-9 # in gigabytes
```
0.4

I guess we need to embed batches of sequences while evotuning instead of performing the full embedding step beforehand.

**Comment by ericmjl** [comment]
Definitely. In-line with what I was thinking here!
