### ISSUE TITLE
get_reps broken for different-length protein lists

### ISSUE THREAD

**Issue by ElArkk** [ElArkk/jax-unirep#77]
The `get_reps` function for different-length proteins is broken both in pip version `1.0.2` and when installing from source.
This cryptic error message shows up:
```
jax.core.UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function.
The functions being transformed should not save traced values to global state. Detail: tracer created on line <stdin>:1 (<module>).
```

Repping lists of same-length sequences still works, so I'm guessing it has to do with repeated calls to our `apply_fun`.
It also might be problem with my current set-up, but I don't think so. 

Didn't have time yet to investigate, but a quick google search led me to [this issue](https://github.com/google/jax/issues/2884) which talks about nested `jit` functions and escaped tracers.

**Comment by ElArkk** [comment]
Just realised that we do test for different length lists in our test suite, so maybe it is my setup after all. @ericmjl does repping work on your side with v `1.0.2`?

**Comment by maximz** [comment]
I'm seeing this on a fresh pip install of v1.0.2 when following the getting started docs. Issue may be upstream: downgrading to v1.0.0 or v1.0.1 didn't fix.

**Comment by maximz** [comment]
The difference between my local environment and the latest successful CI build:

- CI: Jax 0.1.77
- Local: Jax 0.2.0

Downgrading jax fixes it: `pip install --upgrade 'jax<0.2.0' jax-unirep`

Now this works:

```
from jax_unirep import get_reps
h_avg, h_final, c_final = get_reps(["ASDF", "YJKAL", "QQLAMEHALQP"])
```

**Comment by ericmjl** [comment]
That's a good catch, thanks @maximz!

**Comment by ericmjl** [comment]
@maximz because it's bedtime in Basel and @ElArkk isn't going to be awake, I took the liberty of cutting a patch release on my own. Thanks for finding the bug!

**Comment by maximz** [comment]
@ericmjl you bet, and thank you! (it's my first day working with jax-unirep, and i found the docs very clear for getting started)
