### ISSUE TITLE
Clearing GPU memory

### ISSUE THREAD

**Issue by silenus092** [ElArkk/jax-unirep#86]
Hi, 

I have a problem.
Most of the time a GPU didn't release memory after the job is done or If I have to run multiple iterations of `get_reps()` for example, so I have to stop and restart a python kernel or GPU device manually.
I also follow this guideline 
https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html
but it didn't solve my problems. 

The error message,  if I run task continuously 
`
RuntimeError: Resource exhausted: Out of memory while trying to allocate 32698952242 bytes
`

Do you have any idea about how to reset/free GPU memory after each iteration?

Thank you,
Note

**Comment by ElArkk** [comment]
Hi @silenus092 ,

Have a look at this resolved issue https://github.com/ElArkk/jax-unirep/issues/44#issuecomment-625902755 . Let me know if that solution doesn't work in your case.

**Comment by silenus092** [comment]
Hi @ElArkk ,

Nope, that one works for the JAX version before Aug. 

Thus, I trace back to google/jax repo.
I search from both Issues and Pull request tab
Then I found this one 
https://github.com/google/jax/pull/3941
they remove  DeviceValue class and found they use DeviceArray instead.(https://github.com/google/jax/blob/master/jax/interpreters/xla.py)

So I made some modifications to your suggested solution.

```
def reset_device_memory(delete_objs=True):
    dvals = (x for x in gc.get_objects() if isinstance(x, jax.xla.DeviceArray))  # <-- change this 
    n_deleted = 0
    for dv in dvals:
        if not isinstance(dv, jax.xla.DeviceConstant):
            try: 
                dv._check_if_deleted()  
                dv.device_buffer.delete() # <-- change this 
                n_deleted += 1
            except:
                pass
        if delete_objs:
            del dv
    del dvals
    gc.collect()
    return n_deleted
```

And now it works, I already test with GPU/CPU backend

Thank you very much 

Best regards,
Note

**Comment by ElArkk** [comment]
Nice, thank you for posting the updated solution here!
