### ISSUE TITLE
Training mLSTM1900 weights from scratch

### ISSUE THREAD

**Issue by jmahenriques** [ElArkk/jax-unirep#90]
First of all, big fan of your work, jax-unirep has really helped me a lot in embedding sequences and evotuning the original weights. I am currently interested in training the mLSTM1900 weights from scratch using the sequences in UniRef50, just as the original authors did in their work. The main problem that I am facing is that `params=None` in `fit` defaults to the original mLSTM1900 weights instead of using randomly generated weights. This is not true for the other pre-built models (mLSTM64 and 256). I'm definitely not an expert in this field, so please bear with my ignorance, but why is this and how can I go around it?

**Comment by ElArkk** [comment]
Hi @jmahenriques ,

Thanks for the kind words! This behaviour is due to a design decision; we wanted to make it as easy as possible to just evotune the original weights (since that might be what most people would want to do). Having randomly initialized weights is easily accomplished, below a slightly adapted version of the example in the docs:

```python
from jax.random import PRNGKey

from jax_unirep import fit
from jax_unirep.evotuning_models import mlstm1900

init_func, apply_func = mlstm1900()

# The init_func always requires a PRNGKey,
# and input_shape should be set to (-1, 10)
# This creates randomly initialized parameters
_, params = init_func(PRNGKey(42), input_shape=(-1, 10))

sequences = ["HASTA", "VISTA", "ALAVA", "LIMED", "HAST", "HAS", "HASVASTA"] * 5

# Now we tune the params.
tuned_params = fit(sequences, n_epochs=2, model_func=apply_func, params=params)
```

I hope this helps, let me know if you have additional questions.

**Comment by jmahenriques** [comment]
Thank you for your prompt reply @ElArkk, this is great stuff! Just one more thing, how do I go around this: `ModuleNotFoundError: No module named 'jax_unirep.evotuning_models'`?

**Comment by ElArkk** [comment]
Ah damn, I forgot that we did not yet release the newest updates which include the API changes on PyPI, sorry about that. We will do so in the coming days, and then you'll only need to update `jax-unirep` through `pip`. Until then, you'd need to install from source:
`pip install git+https://github.com/ElArkk/jax-unirep.git`

**Comment by jmahenriques** [comment]
Thank you, I suspected installing from source would be the solution and I did try it but I think my sys.path was still putting the PyPI installation on top and that's why the issue remained. I will do it on a clean venv to be sure.

**Comment by ericmjl** [comment]
@jmahenriques hang tight! I'm the blocker to reviewing @ElArkk's PR #88 (with a newborn + full-time job, it's sometimes a struggle to squeeze out time to do code review), but once it's done, we'll cut a release to PyPI, and the `conda` bots will make sure it'll get updated on conda-forge too.

**Comment by jmahenriques** [comment]
No worries @ericmjl, I've got it up and running. I'm now trying to understand why I run out of memory in our GPU nodes even though the program is trying to allocate a lot less than what I'm theoretically allowed (4 GPU, 32 vCPU, 244GB RAM, 64GB GPU RAM each):

```
2020-12-01 12:44:57.813623: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:433] Allocator (GPU_0_bfc) ran out of memory trying to allocate 17.33GiB (rounded to 18602792704)requested by op
2020-12-01 12:44:57.813867: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:441] ****________________________________________________________________________________________________
2020-12-01 12:44:57.813923: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1809] Execution of replica 0 failed: Resource exhausted: Out of memory while trying to allocate 18602792608 bytes.
```

Curiously, it runs on the front-end CPU-only server with no issues. I guess it's time to bother our IT people, I'm probably messing up the submission script somehow :)

P.S.: Congrats on the newborn by the way, I'm a father of 2 small children and I know exactly what you mean. I find it super impressive that you manage to develop jax-unirep on top of all the other big daily responsibilities.

**Comment by ericmjl** [comment]
Mmmm! This is something we've encountered before as well, albeit not on an HPC system but on a single compute node with a single GPU. If you're trying to re-train the mLSTM1900 weights using UniRef50, setting batch size is going to be extremely important. (I've empirically found that a batch size of, like, 22 is the max I can go on a 16GB GPU RAM system.) 

You can also tradeoff speed for dynamic RAM allocation in JAX - an environment variable is needed: https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

A bit of a pro tip here though - on a system that I was using, to get to 1 epoch equivalent via random batches, it'd take half a year to complete. We avoided a lot of complexity by using `vmap` rather than `pmap`, as a common use case we were thinking of was that we'd train disposable weights from scratch for "local" problems, and simply leverage the inductive biases of the model as a way to generate numerical representations that are meaningful. Retraining on the whole dataset is, yes, intellectually interesting, but be prepared to deal with issues of scale. (These are words of a fellow scientist who's burned at least a week trying to get this going.)

Btw, do you know Simone Fulle? I met her at a Proteins GRC before. I think both of you work at Novo Nordisk!

**Comment by ericmjl** [comment]
@jmahenriques small world indeed! :smile: 

> If given the choice I would avoid it altogether and stick with evotuning with peptides/proteins of interest as we've been doing so far, but there's the whole non-commercial license issue regarding the original weights and we need to find a way around it, which may involve training from scratch. That's why I'm playing with it, I need to get a feeling for how hard/expensive this is in order to better assess whether it is worth it to give it a shot or whether we should abandon the idea altogether. Our legal division actually doesn't think the license restricts internal use, but we want to play safe.

Indeed, I hear you on that! The non-commercial license has been on my mind for a while as well. Looking at the license terms, we're allowed to share and adapt, as long as it's not for commercial purposes. I'm not a lawyer, and have no legal training, but in trying to think like one, I would have reached the same conclusion as you would. 

On the other hand, I think starting a "small artisanal batch" evotuning round starting from random weights might be a productive alternative, if you haven't already considered that. I think Randomly generated numbers aren't licensed the way the trained weights are. The biggest effort that really needs to be put into is defining the set of sequences on which evotuning happens. 

I have a hunch, unconfirmed at this point, that evotuning from random weights will be perfectly fine for "local" problems that don't involve all proteins across the tree of life. According to the original paper, this method won't necessarily yield necessarily "the best" performance, but I think for all intents and purposes, it's probably "awesome enough". Have you considered using 
evotuning from random weights as an alternative for your local problems?

**Comment by jmahenriques** [comment]
> I have a hunch, unconfirmed at this point, that evotuning from random weights will be perfectly fine for "local" problems that don't involve all proteins across the tree of life. According to the original paper, this method won't necessarily yield necessarily "the best" performance, but I think for all intents and purposes, it's probably "awesome enough". Have you considered using
evotuning from random weights as an alternative for your local problems?

Indeed. In my opinion, this is the way to go for us. We had a collaboration with the University of Copenhagen, where two MSc students showed that you can achieve fairly similar results if you train from scratch on a much smaller subset of UniRef50 (picked at random). In fact, the quality of their results is largely invariant to the type of RNN and hidden state dimension used. Please take a look at https://github.com/leetemil/unirep_project if you're interested in all the details. I can also give you their thesis if you'd like.

So yes, I have thought about it quite a lot and I do believe that reproducing what these students did (a lot less sequences and possibly much smaller hidden state size) should be our first approach. Simone still wants me to try to train the whole thing from scratch, but I think I will encounter enough barriers along the way to be able to build a case against it. At the end of the day, the performance these students achieved with far less data and simpler models is comparable to the original UniRep and that should be good enough for most purposes.

**Comment by jmahenriques** [comment]
I was testing the code on a set of 400k randomly picked UniRef50 sequences (and another 100k as holdout) and noticed something strange:

```
right-padding sequences: 100%|██████████| 400000/400000 [00:08<00:00, 45660.04it/s]
100%|██████████| 1/1 [00:00<00:00, 14.47it/s]
INFO:evotuning:Random batching done: All sequences padded to max sequence length of 400000
``` 

Why does it say that all sequences were padded to a max length of 400000? These are the top 10 longest sequences in the 400k training sequences [34350, 18562, 18141, 14507, 13100, 11910, 11872, 11103, 10287, 10061]. Shouldn't the padding be to a max length of 34350 instead? 

As a result the memory allocation blows up (trying to allocate >115GB). Could this be a bug?

**Comment by ericmjl** [comment]
@jmahenriques that definitely looks like a bug. @ElArkk, we might want to address this one before we finally cut the 1.x release onto PyPI, I think. I remember the logging messages being a tad troublesome to handle.

**Comment by ElArkk** [comment]
Definitely, thanks @jmahenriques for reporting on this. I just saw that the logging statement has a simple bug, it actually prints the length of the longest length batch instead of the longest sequence (the longest length batch being the only one - containing all the padded sequences - in this case). Not sure if the actual sequences get padded to that length though, or did you check that already @jmahenriques?

**Comment by jmahenriques** [comment]
I just checked and the sequences are being padded correctly, which is a relief. Where I think things go south is in the batching itself.

For me, `training_seqs_batched` is looking very suspicious. It basically tells me that there is a single batch containing 400000 sequences. I'm requesting a batch_size of 25 with batch_method "random". Something must be off with `generate_batching_funcs`, no?

**Comment by jmahenriques** [comment]
Ok, I think I get it. `fit` calls `utils.batch_sequences` regardless of the batch_method selected, and this function batches by sequence length. Since all sequences have already been padded, all of them have the same length and it returns a single batch. Was this intended? I thought the objective was to get N random batches of a given batch size.

**Comment by jmahenriques** [comment]
Given that only ~1% of all UniRef50 sequences are longer than 1500 residues, I've decided to throw them away and now I am able to train the model as originally intended. It takes a massive amount of time to complete each iteration, so I'm abandoning the project as originally devised. I will instead focus on using human sequences below 2000 residues from UniRef50 (latest version). This gives me approximately 80k sequences to train on.

I'm closing this issue as everything works as intended. Thank you a lot of all your technical assistance and scientific input.
